### ISSUE TITLE
Can the stroke go outside of the localBounds?

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#16]
Following the strategy in SpectrumNode, I'm using code like:

``` js
    this.addChild( new Image( canvas.toDataURL() ) );

    // since the Image's bounds aren't immediately computed, we override it here
    this.setLocalBounds( new Bounds2( 0, 0, width, height ) );
```

This generates the gradient used in the paint scenes.  However, afterwards, I add a stroke that goes outside of the local bounds (because the stroke is centered not "inner"):

``` js
    // outline. TODO: is it a problem that this goes outside of the LocalBounds?
    this.addChild( new Rectangle( 0, 0, width, height, { stroke: 'black', lineWidth: 2 } ) );
```

I'm not familiar enough with scenery localBounds to know whether this is asking for trouble.  @jonathanolson can you comment?

**Comment by jonathanolson** [comment]
Local bounds usually do include the stroke (at least with the default Path bounds method).

Scenery (in the general case) can exclude content outside of the local bounds, but this usually doesn't happen. It would generally need to have a layer fitted around it, and Scenery usually provides a few pixels of safety margin for anti-aliasing.

For peace of mind, I'd expand the bounds, or move the rectangle in by 1 pixel. Or just set the local bounds on the image (as the comment would imply) instead of the image's parent.

**Comment by samreid** [comment]
Fixed by setting the localBounds on the image node, thanks for the suggestion @jonathanolson, closing.
