### ISSUE TITLE
Can the billiards tables be bigger?

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#17]
@phetsims/beth-stade said:

> The billiard table when small is hard to see.  Can the squares get any bigger or are we at the max for 20 by 20?

**Comment by samreid** [comment]
@phetsims/beth-stade continued:

> Or could the border the table be slimmed down a speck?
> I find the black pockets distracting on the smaller size tables, so much going on in a small space.  I don't need the black pockets.

**Comment by amanda-phet** [comment]
We had lots of discussions about the size of the billiard table and decided on the maximum 20x20 table size and agreed that the 1x1 table was acceptable. 

I think we need the black pockets because any of those three pockets could be the final one the ball exits through, and it's an important distinction from the original corner, especially as the tables increase in size. I think it's an important point that the ball can _only_ exit through one of those three and never the one it started at!

**Comment by bethstade** [comment]
Yes, 20x20, but perhaps we can tweak the actually visual size as the 1x1 is so very small, or reduce the border a bit.
I do think the black pockets are unneeded and distracting on the small tables, but it's an opinion of course.

----- Original Message -----From: Amanda McGarry notifications@github.comTo: phetsims/proportion-playground proportion-playground@noreply.github.comCc: bethstade stadee@colorado.edu, Team mention team_mention@noreply.github.comSent: Fri, 27 May 2016 20:08:18 -0000 (UTC)Subject: Re: [phetsims/proportion-playground] Can the billiards tables be bigger? (#17)

We had lots of discussions about the size of the billiard table and decided on the maximum 20x20 table size and agreed that the 1x1 table was acceptable.
I think we need the black pockets because any of those three pockets could be the final one the ball exits through, and it's an important distinction from the original corner, especially as the tables increase in size. I think it's an important point that the ball can only exit through one of those three and never the one it started at!
&mdash;You are receiving this because you are on a team that was mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by amanda-phet** [comment]
Didn't see issues with this in interviews. Closing.
