### ISSUE TITLE
Can the spinner show a $ sign?

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#20]
@kathy-phet said:

> Also is it hard for the spinner in the apple scene to have
> 
> $1, $2, $3? 

--- Note --none of these are critical for Wed.  But they would be valued if available.

**Comment by samreid** [comment]
Fixed above.

**Comment by samreid** [comment]
Published in http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.12/proportion-playground_en.html

I'll email @kathy-phet to review.

**Comment by amanda-phet** [comment]
In the 12/22 design meeting we decided not to use $ because it is regional, but instead use a coin as the currency. The mockups in the design doc do not reflect that because I went on leave before finishing them, but there is a mockup in the "next meeting" notes that I created right before going on my leave for discussions that would happen without me. 

I think we should reconsider the currency here and make a final decision about how internationalize-able we want it to be.

**Comment by samreid** [comment]
I have made symbol internationalizable, so that translators could use symbols like £, € or any other unicode symbol or word, and place it before or after the number, or omit it altogether.

**Comment by amanda-phet** [comment]
That seems like a great solution- I didn't realize that was possible. 

Not sure if you're still waiting on @kathy-phet 's review so I'll assign back to you Sam.

**Comment by samreid** [comment]
OK seems good, closing.

**Comment by kathy-phet** [comment]
I do like the solution. It also seems like the translator can then just remove it if there isn't a symbol that makes sense.
