### ISSUE TITLE
Improvements to necklace geometry

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/proportion-playground#22]
As a first small project @andrea-phet will be working on seeing if she can improve the necklace geometry to more closely match the design document.

This issue will be to track progress.

**Comment by samreid** [comment]
The design doc requests the necklace to look like this:

![image](https://cloud.githubusercontent.com/assets/679486/15754730/ddf1f14a-28b6-11e6-98eb-7b8435572ee2.png)

The simulation currently looks like this:
![image](https://cloud.githubusercontent.com/assets/679486/15754754/f67919be-28b6-11e6-8719-0b3f341fe335.png)

Don't worry about the overall size and scaling.  Note that the requested one is more "lumpy" and has a blank space at the top, this space is so that students will have a natural starting point for counting.

The file where this is coded is:
proportion-playground/js/explore/view/necklace/StaticNecklaceNode.js

**Comment by andrealin** [comment]
@ariel-phet @samreid Here is my progress so far:

For the gap in the necklace that students use to start counting, I added one to the number of points `var numberPoints = numBeads + 1;` and chose the last-first pair to be the gap. I moved the center of the last-first pair of vertices out a bit, to match the design.

```
        // if it is the last pair, increase magnitude of the center for a gap
        else {
            center.addXY( 5 * Math.cos( center.angle() ), 5 * Math.sin ( center.angle() ) );
        }
```

To make the necklace more lumpy, I chose a random point inside the polygon skew on the vertices / make them gravitate towards the point. Here is the code, it would more or less replace the `//randomize vertices` code

```
      // using gravity of a random point to make the necklace look more natural

      // find the apothem of the polygon, see http://www.mathopenref.com/apothem.html     
      var apothem = R * Math.cos( Math.PI / numberPoints );

      // choose a radius in a range 0.2 - 0.5 of the apothem
      var randomRadius = ( Math.random() * 0.3 + 0.2 )* apothem;      
      var randomAngle = Math.random() * Math.PI * 2;      
      var gravitate = Vector2.createPolar( randomRadius, randomAngle );   

      var zero = Vector2.createPolar ( 0, 0 );

      // for debugging
      console.log( 'radius' + Math.round(R) );
      console.log( Math.round( apothem ) + " becomes " + Math.round( randomRadius ) );

      // change vertices according to gravitate
      for ( var i = 0; i < numberPoints; i++ ) {
        var perfectPoint = Vector2.createPolar( R, i * angleBetweenPoints );    
        var difference = gravitate.distance( perfectPoint );        
        var amount = Math.pow( ( apothem - difference ), 2); // is power to the 2 good?     

        var newRadius = R - amount / R; // what is the best ratio?

        var point = Vector2.createPolar( newRadius, i * angleBetweenPoints); // what is the     
        vertices.push( point );
      }
```

This would not be on the master branch, I drew a blue dot at the center of the polygon and a pink dot for the skewing point to show what is happening. Necklaces look like this:
![image](https://cloud.githubusercontent.com/assets/7988696/15834961/1e9c8c32-2beb-11e6-9606-b04b75a9ba2f.png)
![image](https://cloud.githubusercontent.com/assets/7988696/15835442/40f5ca94-2bed-11e6-9db5-8d58c1f1fc8e.png)
![image](https://cloud.githubusercontent.com/assets/7988696/15835063/88eedb58-2beb-11e6-83fb-8b1b007249ae.png)

Improvements
- Fewer sided polygons look angular rather than like a smooth necklace
- I am thinking about adding more skews, tweaking with the strength of the skew, etc.
- Not sure how to make the beads closer together to look more like the design and prevent them from overlapping at the same time.
- It would be nice to rotate the necklace 90 degrees so the gap starts at the top like the design.

**Comment by samreid** [comment]
@andrea-phet thanks for the status update, it is looking good so far.  Please feel free to check in to master if you wish, since this seems like a good direction to go in.  Once you are ready for a more thorough review, please let me know and I'll take a closer look.

**Comment by amanda-phet** [comment]
As far as matching the design doc... the necklace doesn't need to be too lumpy, but the space at the top is definitely important. It's all looking really good to me!

**Comment by andrealin** [comment]
Since the last status update, I made the necklace line in the gap and on smaller polygons more smooth. I resized the necklace to prevent overlap, and committed the changes to master https://github.com/phetsims/proportion-playground/commit/31aeeb0d75234cb4f23d3fd8e167a16b5f0f2026 (also above).

Saw #8 so the single beaded necklace now looks like this:
![image](https://cloud.githubusercontent.com/assets/7988696/15976971/29223b90-2f13-11e6-9f75-07cd3d2cb833.png)

This is ready for review and deployment!

**Comment by samreid** [comment]
Nice work @andrea-phet, I published a version with these changes here:
http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.13/proportion-playground_en.html

@amanda-phet @kathy-phet and @phetsims/beth-stade please review at your convenience.

**Comment by amanda-phet** [comment]
I think it's looking really good! 

One question I have for the team (and maybe want to extend to other design team members) is whether we want necklaces of the same size to be the same shape. Or, if two necklaces with identical bead patterns should have the same shape as well. Here is one example of looking different:
<img width="500" alt="screen shot 2016-06-13 at 9 43 21 am" src="https://cloud.githubusercontent.com/assets/7852916/16013619/693ed578-314b-11e6-9b83-5985b8989c0d.png">
It seems possible that a bead pattern could become construed, and may lead to misconceptions if I'm glancing and not counting carefully: 
<img width="486" alt="screen shot 2016-06-13 at 9 44 31 am" src="https://cloud.githubusercontent.com/assets/7852916/16013644/7cad7efc-314b-11e6-806b-29d3128f2dbb.png">

**Comment by ariel-phet** [comment]
It does seem important to implement a rule that if the necklaces match (20 & 5) for instance we match the two necklaces. I think @andrea-phet could create a simple rule that if one necklace is already set to a particular value if the other necklace is set to that same value the second necklace borrows the pattern from the first.

**Comment by samreid** [comment]
Another possible way to implement this would be to choose randomNumber, randomAngle and randomRadius deterministically as a function of the total number of beads (rather than randomly each time).  Then the left/right necklaces would match when their number of beads is the same.  I agree that the necklaces should have the same shape when the number of beads is the same, @andrea-phet you can decide the best way to accomplish this.

**Comment by andrealin** [comment]
Will do. I will be away from my computer this week, so it is not too late for me to accomplish this next week?

**Comment by ariel-phet** [comment]
@andrea-phet yes, no rush

**Comment by andrealin** [comment]
I have changed the code so that necklaces with identical bead patterns have the shape. Before I commit, here's an idea: what if necklaces with the same proportion also had the same shape? It's pretty subtle, but it would look something like this:

![image](https://cloud.githubusercontent.com/assets/7988696/16201705/d808a9f0-36cf-11e6-9391-3710e18eeee1.png)

All necklaces with only round beads would look like this:
![image](https://cloud.githubusercontent.com/assets/7988696/16202024/3b55eeb8-36d1-11e6-9ae4-6f85a2d1f354.png)

And necklaces with only square beads would look like this:
![image](https://cloud.githubusercontent.com/assets/7988696/16202080/6e8955c2-36d1-11e6-8ff9-a1a38bc2a7d1.png)

**Comment by amanda-phet** [comment]
> what if necklaces with the same proportion also had the same shape? 

I think that's a great idea! The examples you showed illustrate this really well.

**Comment by andrealin** [comment]
@amanda-phet if you feel this is all good, feel free to close.

**Comment by amanda-phet** [comment]
I can't see this until I'm on campus (tomorrow), so I will play with it a bit then and close the issue if it all seems good!

**Comment by amanda-phet** [comment]
Looks great to me. Your ideas were spot on and I think they were executed well!
