### ISSUE TITLE
Refactoring of the necklace pattern search

### ISSUE THREAD

**Issue by andrealin** [phetsims/proportion-playground#23]
In proportion-playground/js/explore/view/necklace/StaticNecklaceNode.js I saw this algorithm to search for a bead pattern:

```
      // Brute force search for pattern
      var solver = function() {

        for ( var m = maxBeads; m >= 1 && !match; m-- ) { // search for many pattern occurrences first
          for ( var na = 0; na <= maxBeads && !match; na++ ) {
            for ( var nb = 0; nb <= maxBeads && !match; nb++ ) {
              if ( m * na === a && m * nb === b ) {
                return { m: m, na: na, nb: nb };
              }
            }
          }
        }
        assert && assert( false, 'no solution found' );
      };
```

I think a faster way is to use one for loop to find the greatest common divisor:

```
      /**
       * Searches for the bead pattern to be displayed by finding the greatest common divisor. 
       * @returns {Object} - dictionary for m, na, and nb. m is the number of patterns, na is the number of round beads per pattern, and nb is the number of square beads per pattern.
       * @private
       */ 
      var solver = function() {

        if ( a === 0 || b === 0 ) { // m is 1 if a or b are 0
            return { m: 1, na: a, nb: b }; 
        }

        for ( var m = a; m >= 1; m-- ) { // search for greatest common divisor of a and b
            if ( a % m === 0 && b % m === 0 ) {
                return { m: m, na: a/m, nb: b/m };
            }
        }

        assert && assert( false, 'no solution found' );
      }
```

**Comment by ariel-phet** [comment]
@samreid can you review the above solution and give any comments, @andrea-phet and I looked together to try to follow the style guidelines and good commenting habits. Please point out anything that should be fixed, or improved!

**Comment by ariel-phet** [comment]
Marking as high priority since this should be quick and best to start good habits early

**Comment by samreid** [comment]
Sure, I'll take a look!

**Comment by samreid** [comment]
The algorithm looks great, nice work!  I tested it for all 441 combinations of a and b and it is giving equivalent results to the brute force search (aside from a===0 or b==0 which is fine).

Regarding the commenting:
- This function has local scope, thus the `@private` annotation is redundant and should be removed. 
- Our style guide http://bit.ly/phet-development-overview recommends limiting line length to 120 characters, so that long comment line should be broken up.
- Regarding this line:

``` js
        if ( a === 0 || b === 0 ) { // m is 1 if a or b are 0
          return { m: 1, na: a, nb: b };
        }
```

It is clear from the code that m is 1 if a or b are zero--it would be better to explain this in higher-level terms, such as "If there is only one type of bead, then there is only one pattern occurrence."
- Generally, it is better to put comments above like so:

``` js
        // search for greatest common divisor of a and b
        for ( var m = a; m >= 1; m-- ) { 
          if ( a % m === 0 && b % m === 0 ) {
            return { m: m, na: a / m, nb: b / m };
          }
        }
```

Trailing comments would be best when they regard a minor detail and only apply to a single line. (And even then sometimes a preceding line comment is better.)

One last remark: at the top of this issue the code example was written using `````, but if you use ````js` to start a code block and ````` to end it, then GitHub will mark it up with JS syntax highlighting.

Nice work @andrea-phet, reassigning to you to proceed.

**Comment by andrealin** [comment]
Closing this.
