### ISSUE TITLE
White paint doesn't show up too well on the background

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#4]
White paint doesn't show up too well on the bright background:

![image](https://cloud.githubusercontent.com/assets/679486/15448680/9fc814ca-1f25-11e6-9e15-65744cb1e5c9.png)

Tagging @kathy-phet @ariel-phet @amanda-phet @jonathanolson @krhensberry for suggestions.  Do Beth or Ian have github handles?

**Comment by kathy-phet** [comment]
Hi Sam,

Don't worry about this right now. We can work on making this more visible with a stroke or a change in the background color down the road.

K

Sent from my iPhone

On May 21, 2016, at 7:32 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:

White paint doesn't show up too well on the bright background:

[image]https://cloud.githubusercontent.com/assets/679486/15448680/9fc814ca-1f25-11e6-9e15-65744cb1e5c9.png

Tagging @kathy-phethttps://github.com/kathy-phet @ariel-phethttps://github.com/ariel-phet @amanda-phethttps://github.com/amanda-phet @jonathanolsonhttps://github.com/jonathanolson @krhensberryhttps://github.com/krhensberry for suggestions. Do Beth or Ian have github handles?

##

**Comment by amanda-phet** [comment]
That is also not the final "splotch". We will try to give it a little more dimension, and a shadow could help with this problem.

Get Outlook for Androidhttps://aka.ms/ghei36

On Sat, May 21, 2016 at 7:13 AM -0700, "kathy-phet" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Sam,

Don't worry about this right now. We can work on making this more visible with a stroke or a change in the background color down the road.

K

Sent from my iPhone

On May 21, 2016, at 7:32 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:

White paint doesn't show up too well on the bright background:

[image]https://cloud.githubusercontent.com/assets/679486/15448680/9fc814ca-1f25-11e6-9e15-65744cb1e5c9.png

Tagging @kathy-phethttps://github.com/kathy-phet @ariel-phethttps://github.com/ariel-phet @amanda-phethttps://github.com/amanda-phet @jonathanolsonhttps://github.com/jonathanolson @krhensberryhttps://github.com/krhensberry for suggestions. Do Beth or Ian have github handles?

## 

You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHubhttps://github.com/phetsims/proportion-playground/issues/4

##

**Comment by samreid** [comment]
For drawing the color of the paint splotch, it is very convenient for it to be a vector definition (shape only).  If we use a raster, then we lose the ability to easily/quickly/smoothly change the color.  That being said, we could show the shadow/dimension in code or with another vector shape.

**Comment by samreid** [comment]
I published a dev version that shows the paint, you can see the color issues here:
http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.2/proportion-playground_en.html

Note: this uses cyan instead of blue so that color mixing can be done in RGB space.

**Comment by samreid** [comment]
A thin black outline seems great:
![image](https://cloud.githubusercontent.com/assets/679486/15455231/c52fd176-200b-11e6-9fca-7132d8920d93.png)

![image](https://cloud.githubusercontent.com/assets/679486/15455235/cd53bb92-200b-11e6-82e0-0c7d9e6376ea.png)

However, there is a glitch in the svg where there is a horizontal bar appearing at the top left.

**Comment by samreid** [comment]
I fixed the glitch and will move forward with an outline in the next version.
