### ISSUE TITLE
Add crate and coin artwork to Apple scene

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#47]
I will upload the .ai assets and email JO the exported images. The three pieces of artwork are 
* coin 
* back of crate
* front of crate 

![screen shot 2017-01-19 at 11 11 53 am](https://cloud.githubusercontent.com/assets/7852916/22119935/ae38d66e-de3a-11e6-93b7-b039b80e1145.png)

The artwork to implement may require some tweaking to the code: 
1. 3D coin might need a new vertical offset so that it stacks nicely
2. Apples stack slightly differently to account for the perspective in the crate

**Comment by jonathanolson** [comment]
A few notes:

1. I'll need a higher-resolution coin image. It gets blurred pretty badly (see below in images)
2. Having a darker outline on the coin would make it easier to be able to count visually.
3. Green apple is taller, which looks weird when in the box (see https://github.com/phetsims/proportion-playground/issues/51)
4. The "Cost per Apple" panel totally gets in the way as @amanda-phet predicted today. I have a general proposal (committed) for its approximate layout.

Layout when the box is added around the apples (no room above for the cost-per-apple unless the apples are made way smaller):
![screen shot 2017-01-19 at 10 11 16 pm](https://cloud.githubusercontent.com/assets/480878/22137128/6c323e70-de96-11e6-9a37-aad891eaabe3.png)

Proposed location for the cost-per-apple readout, so that it's similar to where a price would be for apples at a fruit stand:
![screen shot 2017-01-19 at 10 22 59 pm](https://cloud.githubusercontent.com/assets/480878/22137156/89a6aca2-de96-11e6-961f-fda4d2a4beec.png)

The sizes/appearance of things could definitely be tweaked if that layout is used (make it look more like a price label). I'll also probably fine-tune the alignment of the coins and apple-box vertically if something similar is used.

Thoughts?

**Comment by kathy-phet** [comment]
I like the proposed location of the price label. I think some tweaks there could help - either making the crate a bit taller so that the labels sits entirely on the wooden part or something else. I do like the font size so wouldn't want to go much smaller. 

Agreed coins need higher res ... it needs to be easy to make out one coin from the next. 

Overall, great to see the artwork in here!

**Comment by jonathanolson** [comment]
> making the crate a bit taller so that the labels sits entirely on the wooden part

I like that idea.

> I do like the font size so wouldn't want to go much smaller.

I knocked it down from 30 to 25 for that screenshot, so it could always grow a bit also.

**Comment by amanda-phet** [comment]
Darker coin outline 
![screen shot 2017-01-20 at 8 56 43 am](https://cloud.githubusercontent.com/assets/7852916/22155925/63161124-deee-11e6-89f0-8ad7d4feadd9.png)

Taller crate to fit label + two options for labels
![screen shot 2017-01-20 at 8 55 07 am](https://cloud.githubusercontent.com/assets/7852916/22155931/671e72b6-deee-11e6-95ab-e354c26dc0bf.png)

Thoughts?

**Comment by kathy-phet** [comment]
+1 

For labels, I like both, so leave it up to you.

**Comment by amanda-phet** [comment]
I like the label on the right. 

I'll email assets to @jonathanolson now (and export at a higher res).

**Comment by jonathanolson** [comment]
The coin artwork still needs to be bigger (let me know if the sent artwork is way higher resolution, web Outlook mail may have messed it up).

I tried to get Illustrator, but the licensing website is down for maintenance.

![coin](https://cloud.githubusercontent.com/assets/480878/22179134/9cae5620-e007-11e6-9736-861249d64df6.PNG)

**Comment by jonathanolson** [comment]
Implemented the new crate label, still waiting on the higher-resolution coin graphic.

**Comment by amanda-phet** [comment]
The new coin is 126x90. What would be a good resolution? I'll email you now one that is 251x180. I can make it any resolution so it would be helpful to know what is ideal. 

The coin also has some "roughness" in the design, so if it's distracting I can try to smooth it out. 
<img width="396" alt="screen shot 2017-01-24 at 10 20 35 am" src="https://cloud.githubusercontent.com/assets/7852916/22258442/d4d4197c-e21e-11e6-8ac2-2ca81848ea6f.png">

**Comment by jonathanolson** [comment]
The provided resolution looks good. Let me know how it looks, the "roughness" looks like the source is a bit pixelated (but looks fine now on my screen).

**Comment by amanda-phet** [comment]
I think it looks good. Thank you!
