### ISSUE TITLE
alternate background color for Predict screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#61]
See issue #57 

Here is DFE7FF. Seems like a decent color to me, although I might change the color of the visibility button. 
![screen shot 2017-01-31 at 10 20 14 am](https://cloud.githubusercontent.com/assets/7852916/22477283/ac9aa406-e7a2-11e6-8881-7fd8fbf9d8b8.png)

@kathy-phet and @ariel-phet if you get a chance to play with the color profile editor let me know if you have another background color to consider!

**Comment by ariel-phet** [comment]
@amanda-phet as long is it does well with color blind tests, I do not have a strong preference. I might go a shade lighter than you have for more contrast, but I defer to your judgement.

**Comment by kathy-phet** [comment]
@amanda-phet - I checked out this color in the sim and I like it. It feels like it goes well with the other background color to me - and looks good with all the options. Note that I could not figure out how to use the code you provided with JO's tool -- so I had to use another tool to figure out the RGB. I think I'm just going a bit nuts because I know when we looked at it in the meeting there was a way.

**Comment by jonathanolson** [comment]
Chrome on Windows didn't have a way to input a hex color (sorry!) Generally the first google hit (when googling a color code) has a ton of information on it, including the RGB.

Above color: #DFE7FF (223 red, 231 green, 255 blue)

I also feel like the color's a bit strong and dark (a more light less saturated color lets the colors of the sim pop), so I'd like to propose #EAEEFD (red 234, green 238, blue 253)

**Comment by amanda-phet** [comment]
>I'd like to propose #EAEEFD (red 234, green 238, blue 253) 

Looks great to me! Let's move forward with that color on the background of the Predict screen.

The background of the screen icons will need to be changed as well.

**Comment by kathy-phet** [comment]
FWIW, I do prefer the deeper blue because it makes the number boxes really pop more where as the fainter shade they have less contrast, and in this sim the number spinners is very important to attend to. And to my eye the colors all still pop nicely and some more so, with the deeper shade. That said, I can be OK with the fainter color. 

I also think we need to make sure to keep in mind Trish's often comment. That when the background is a nice solid color - it works well on the projection screen even in a sunlit room. The fainter it is (or if pure black) than it doesn't not work as well under those circumstances that are often occuring in classrooms. If the room is sunlit, the contrast been the background and the number spinners could be worse than with the deeper colored background.

**Comment by amanda-phet** [comment]
Let's try out these colors on a projector to see what it looks like but we will still move forward with the lighter purple for now.

**Comment by jonathanolson** [comment]
Changed.

My MacBook has those color issues, so can others see how it looks? On my screen, the blue-ish background color looks weird (to me) with the blue predict button.

Thoughts?

**Comment by amanda-phet** [comment]
I don't really like it now. We could change the button to be yellow since we know that the color looks decent with all of the scenes. Thoughts, @kathy-phet ?

**Comment by amanda-phet** [comment]
I believe the background color has been accepted by everyone at this point so I will close this issue and make a new one for the button color.
