### ISSUE TITLE
Confirm/Correct behavior on Predict Screen (Eyeball button out of sync)? 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/proportion-playground#63]
It seems like the eyeball button is out of sync (it shows the current state not the future state). Should it not show the button that would make the beads visible as opposed to the one that would make them invisible when it shows up? It's not the action that is out of sync, its just that I thought the images would be flip-flopped from what is there now?  
(Seem image .. to me I look at this and it sort of says "hide the necklace" with the current button image). 
![image](https://cloud.githubusercontent.com/assets/5096804/22800110/7c8469da-eec5-11e6-8929-298e62b94f81.png)

**Comment by amanda-phet** [comment]
I wondered about this in Function Builder, as well. I've been trying to find design resources for help in determining how to use this icon but haven't had luck yet. We do know in interviews students weren't confused about what this button did (in either sim), but it would be good to use the eye and eye-slash correctly. I will see what Dave has to say from a design perspective.

**Comment by kathy-phet** [comment]
I don't know the source of this -- but looking at some implementations ... here are images that show the opposite behavior to what we are currently using. I think it should represent the action it will do -- not what the current state is (personally): 
![image](https://cloud.githubusercontent.com/assets/5096804/23136941/7acd7844-f75c-11e6-8463-777c29a1141d.png)
![image](https://cloud.githubusercontent.com/assets/5096804/23137045/05d41ef2-f75d-11e6-9291-d02222a2a6dc.png)

**Comment by jonathanolson** [comment]
I've seen both styles. Some use the button to show what the action will be (show or hide), but some use the presence of the slash to indicate the current status. I think Photoshop had a radio button for layer visibility where a normal eye on the button meant it was visible.

The way the button currently appears (to me), it looks more like it is trying to show the action that will happen (seems somewhat reversed). This is probably because the slash looks like a part of the eye graphic.

**Comment by amanda-phet** [comment]
I'd be fine with switching it but would also want to make that change on Function Builder as soon as possible so that our sims are consistent.

**Comment by kathy-phet** [comment]
I vote for the switch. @amanda-phet - Can you check in with Chris too to see what he thinks about Function Builder in terms of this question?

**Comment by amanda-phet** [comment]
Email Chris. 

@jonathanolson can you please make this change to the icons?

**Comment by phet-steele** [comment]
@amanda-phet @kathy-phet @jonathanolson I'd like to put in my two cents real quick. I believe we should leave the button as is.

I'd say we should keep the decision about the consistency of this button internal to PhET design. PhET has two prominent buttons that show the current state of the button, not the future:

<img width="258" alt="screen shot 2017-02-21 at 10 15 10 am" src="https://cloud.githubusercontent.com/assets/5863899/23176333/c77f5298-f81f-11e6-99dd-49c827c28cc8.png">

In my opinion, these buttons in the screenshot and the reveal button have similar interactivity (toggle the state of one button back and forth). The audio button shows the current state of the audio in the sim while the timer button shows the current state of "Will you be tracking a best time?" So too should the reveal button show the current state of "reveal".

I think we should reserve the case of a button showing the future state for sims that use a button to affect a "running" property. For example, any sim that uses a play/pause button where "Pause" is shown when the sim is playing and vice versa, or even FAMB's first screen where you use the button to get the sim "running" on the first screen:

<img width="666" alt="screen shot 2017-02-21 at 10 22 46 am" src="https://cloud.githubusercontent.com/assets/5863899/23176320/be0efb82-f81f-11e6-9b65-b8fa574d2161.png">

Proportion Playground has no "running" property (except for the billiards scene, which is a one off that would be okay if it had a reveal button that acted like the other scenes).

There is another argument I hesitate to bring up but I'll do it anyway. It's the argument for accessibility, and a sort of weak one at that. People using screen readers would want a description of what the button is and is doing. If we keep the button behaviour as it is, the screen reader would give an accurate description of the current state of the sim. We would probably want to avoid giving them a description of the future state of the sim. For example (and I'm probably very wrong about the syntax of descriptions, but ignore that),

"[Object] hidden. Reveal toggle button",

would be the description given when nothing is revealed. The state of the button would match the description. If we flipped the behaviour of the button (to not have a slash when things are hidden), there would be confusion in a11y development. We would have to write a "hidden" description for the "no slash" state, and a "revealed" description for the "slash" state. Seems backwards to me.

**Comment by kathy-phet** [comment]
We could redesign as a toggle switch or two toggle buttons as in color vision. It just feels like right now the action and visual are confusing me because in my mind as I use the sim I do see this as an action button (show me the necklace) not a state button.

Kathy

Sent from my iPhone

On Feb 21, 2017, at 10:47 AM, phet-steele <notifications@github.com<mailto:notifications@github.com>> wrote:


@amanda-phet<https://github.com/amanda-phet> @kathy-phet<https://github.com/kathy-phet> @jonathanolson<https://github.com/jonathanolson> I'd like to put in my two cents real quick. I believe we should leave the button as is.

I'd say we should keep the decision about the consistency of this button internal to PhET design. PhET has two prominent buttons that show the current state of the button, not the future:

[screen shot 2017-02-21 at 10 15 10 am]<https://cloud.githubusercontent.com/assets/5863899/23176333/c77f5298-f81f-11e6-99dd-49c827c28cc8.png>

In my opinion, these buttons in the screenshot and the reveal button have similar interactivity (toggle the state of one button back and forth). The audio button shows the current state of the audio in the sim while the timer button shows the current state of "Will you be tracking a best time?" So too should the reveal button show the current state of "reveal".

I think we should reserve the case of a button showing the future state for sims that use a button to affect a "running" property. For example, any sim that uses a play/pause button where "Pause" is shown when the sim is playing and vice versa, or even FAMB's first screen where you use the button to get the sim "running" on the first screen:

[screen shot 2017-02-21 at 10 22 46 am]<https://cloud.githubusercontent.com/assets/5863899/23176320/be0efb82-f81f-11e6-9b65-b8fa574d2161.png>

Proportion Playground has no "running" property (except for the billiards scene, which is a one off that would be okay if it had a reveal button that acted like the other scenes).

There is another argument I hesitate to bring up but I'll do it anyway. It's the argument for accessibility, and a sort of weak one at that. People using screen readers would want a description of what the button is and is doing. If we keep the button behaviour as it is, the screen reader would give an accurate description of the current state of the sim. We would probably want to avoid giving them a description of the future state of the sim. For example (and I'm probably very wrong about the syntax of descriptions, but ignore that),

"[Object] hidden. Reveal toggle button",

would be the description given when nothing is revealed. The state of the button would match the description. If we flipped the behaviour of the button (to not have a slash when things are hidden), there would be confusion in a11y development. We would have to write a "hidden" description for the "no slash" state, and a "revealed" description for the "slash" state. Seems backwards to me.

**Comment by amanda-phet** [comment]
Thanks @phet-steele . I also discussed this with Chris and was reminded about why we made that decision in Function Builder and why we should keep this button the way it is. Since these are "toggle buttons", rather than "command buttons", the convention is to show the current state. 

We could consider a different interaction altogether, but I will remind everyone that in interviews students did not show confusion with the button and used it just as we would expect.

**Comment by kathy-phet** [comment]
OK, I will try to reorient the way my brain interprets these buttons. I naturally view them as a command, myself.

**Comment by amanda-phet** [comment]
Just came across another example of this sort of toggle button and it does not reflect the current state... so it seems that there is just a lot of inconsistency. 
![screen shot 2017-02-22 at 10 46 47 am](https://cloud.githubusercontent.com/assets/7852916/23224641/697ec570-f8ec-11e6-91cf-1ce180604669.png)


However, since our sound and timer buttons function a certain way already, I still think we should be consistent with those.

**Comment by kathy-phet** [comment]
I think we need to be consistent with the eyeball icon ... but I think the context really sets the expectations. For the timer, it is working as I expect it to right now. It's just that in the proportion screen the eye feels much more like an action I will take than a state to me. The fact that it is a physical button - like the go button - contributes to this feeling for me.

**Comment by amanda-phet** [comment]
Since this sim is wrapping up, we need to make a decision on this issue. 

My preference is to leave the button the way it currently behaves, which is consistent with all of our other "toggle buttons." Since students used the button appropriately in interviews, I am not overly concerned about their interpretation. 

Since we use this visibility icon in other sims that are coming to the table soon (Area Model Multiplication and Function Finder), we should use those sims as opportunities to revisit this discussion. Perhaps for visibility, a physical button should not be used, and it might be more appropriate to have a flat button, or toggle, or scene selection-style button. But if we are going to use the physical button I'd prefer to keep it consistent with other similar buttons.

**Comment by kathy-phet** [comment]
Amanda, I thought we had discussed a few weeks ago on the phone and you had decided to change it? 
If you've changed your mind, we can leave it for now, but let's continue to discuss as situations arise and be open to revisiting it across the sims. 

In this context, I really don't see it as a toggle of state "hidden"/"visible" and find it less intuitive. I see it, and would prefer students to actually experience it, as an active action - that is "hide" / "show". The button could be defined as the more active action, not a visibility toggle. 

The use in area model is interesting. It can be interpreted as both an "action" and a "state" button. Since when you click it, it has the slash eye it is acting as "hide" action or set to "invisible". But then it also stays that way with a highlight around it so it is indicating that that is what you are on. The challenge with the current button design is that we are reusing the same button ... I think design wise we do want it to be a single "fire" like button for this and not two buttons. 

Can you plan to have it as a side question to ask students in interviews to see what they would find more intuitive. I know they used it OK, but I'd like to hear more about which they would find more intuitive when they go to make sense of the icon visuals and actions and timing that happen when you click it.

**Comment by amanda-phet** [comment]
I'm sorry, we probably did discuss it and since I never responded to the issue so I forgot. 

I am definitely open to revisiting the issue and directly asking students in future interviews to explicitly look at the button. I think a solution in the future will be to not use this kind of button and finding another way of toggling visibility. 

I just had another thought- the other uses of toggle buttons are square/rectangular, rather than circular (level selection screen, Function Builder mystery screen). Would changing the shape of the button change how it feels to you? It would definitely make it *even more* consistent with the other uses and separate it from other round "fire" buttons.

**Comment by kathy-phet** [comment]
I don't think the shape would make much difference, but you can try it. 

I actually like it feeling like an active action button - so as opposed to making it feel more passive readout, I would favor thinking about designs that would allow it to be an action ... especially in the context of the use in this sim.

**Comment by amanda-phet** [comment]
I would like to leave the button as-is, and will plan to ask students in future interviews to specifically look at this button. @amyh-phet and @arouinfar if you have any upcoming interviews please let me know so we can discuss showing Proportion Playground, otherwise the next round will probably be for Area Model this summer.
