### ISSUE TITLE
Reduce NumberPicker delay to make changes slower

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/proportion-playground#70]

**Comment by jonathanolson** [comment]
Implemented a 2x slowdown, assigning for review.

**Comment by ariel-phet** [comment]
@jonathanolson still feels a little fast on my pull from master, please slow down another 2x

**Comment by jonathanolson** [comment]
Having some issues deploying a dev version from this computer, but the second doubling has been committed (phettest would work).

Will plan a dev version after cleanup is complete.

**Comment by amanda-phet** [comment]
Are we talking about fire and hold on a spinner? I just looked at it now and wouldn't make it any slower. If someone wants to get to a specific ratio this is incredibly annoying. Why are we slowing this down?

**Comment by phet-steele** [comment]
@ariel-phet @jonathanolson slowing the spinner down almost feels pointless? I can manually click the spinner faster than fire and hold is going at this point. If the idea was to help performance by slowing the rate at which the pickers change, I don't think this is the right road to go down (since manual clicks can/will be faster).

**Comment by phet-steele** [comment]
Time to go from 0 - 20:

Manual clicks: 3 seconds
Fire and hold after changes: 8 seconds
Fire and hold BEFORE changes: 2 seconds

I'm pretty sure the point of the "fire and hold" design is to make it faster to move within a spinner's range, but it takes 5 extra seconds with these slow downs.

**Comment by ariel-phet** [comment]
@amanda-phet slowing this down because there are some animation performance issues on iPad2, the fire on hold rate was a bit too fast before. Just dialing it in

@phet-steele I think it is OK if the fire on hold is about as fast as "quick clicking". Quick clicking for those with less nimble fingers is more around 4 or 5 seconds for that range.

@jonathanolson lets go back to aound the previous slow down (I think a factor of about 2.5x slower than the original will be good).

**Comment by jonathanolson** [comment]
Changed interval back to 2.5x slower.

**Comment by jonathanolson** [comment]
@amanda-phet and @phet-steele, is the current behavior what is desired, or should I make changes?

**Comment by amanda-phet** [comment]
The current behavior looks fine to me, and if it helps with performance I think it's worth it.

**Comment by phet-steele** [comment]
FWIW, I'm still quite against this. I don't see the performance gain one way or the other. Simply from testing between dev.23 and dev.25 (w/ and w/o the change) the sim still crashes all the same. If anything, a slower interval is what feels like slower performance, since it feels like the sim is struggling to chug along. This perception stems from the fact that manual pressing is still ***so*** much faster. @ariel-phet I swear I'm not clicking unreasonably fast, and I'm especially not tapping too fast on a touch screen. I'd advocate to spend the time fixing what's broken instead of masking it. A useless mask at that since crashing still occurs with fire and hold and/or manual.

**Comment by jonathanolson** [comment]
While the crashing seems like a potentially separate issue, the timer delay (now that I've been working more with it) feels oppressively slow on any fast device.

I'd personally rather the sim feels normal/smooth on most devices than slowish on everything.

Maybe it would be worth time looking to detect old iPad versions to remove the gradients and see if that helps performance? Maybe whatever is done to fix the crashing will help? Not sure.

Thoughts?

**Comment by ariel-phet** [comment]
@jonathanolson first fix the crashing, and then lets talk.

Edit: also the fire on hold is not a "key" feature for this sim in my opinion. But crashing is not acceptable. I would prefer not to detect old iPad versions. I think most students are not going to be clicking blazing fast, that is not really the point of the sim. So crashing is the first thing to address, once we fix that lets see where we are at.

**Comment by amanda-phet** [comment]
Where does this issue currently stand? Are we nixing the spinner slowdown since it doesn't help with performance? If so, I believe it still needs to revert back to the normal speed.

**Comment by amanda-phet** [comment]
Where does this issue currently stand? Are we nixing the spinner slowdown since it doesn't help with performance? If so, I believe it still needs to revert back to the normal speed.

**Comment by jonathanolson** [comment]
I believe the latest patch helped out performance. I went back and tested with no delay, and I feel strongly that the sim feels significantly slower WITH the delay. Reducing the delay makes the sim "feel" faster.

I've (for now) committed a change to revert this back to the original value so it can be tested with the now (somewhat better) performance.

**Comment by phet-steele** [comment]
@ariel-phet @amanda-phet, how doth the spinners fare?

**Comment by ariel-phet** [comment]
Performance feels quite smooth on iPad2 now. Closing
