### ISSUE TITLE
Better look for a necklace with one bead

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#8]
The design doc calls for this:

![image](https://cloud.githubusercontent.com/assets/679486/15490424/0a90c026-2125-11e6-871d-caff7c41ae73.png)

**Comment by samreid** [comment]
Not perfect, but a step in the right direction:

![image](https://cloud.githubusercontent.com/assets/679486/15516744/79c796ea-21b1-11e6-967b-b41a20066d44.png)

**Comment by amanda-phet** [comment]
Thanks for making an issue for this. What you have looks great to me (it doesn't need to look exactly like the mockup). On a related note, we want all of the necklaces, regardless of size, to have a gap so that it's easy to have a universal spot to start counting from. 

The mockup is not perfect and might be too subtle, but this is sort of what I mean:
<img width="105" alt="screen shot 2016-05-25 at 3 28 27 pm" src="https://cloud.githubusercontent.com/assets/7852916/15556883/6a9cee7c-228d-11e6-9e27-8eb450fbe28b.png">

**Comment by andrealin** [comment]
The commit above makes the necklace with one bead look more like the design, and more importantly it adds a gap situated at the top of the necklace. This was also discussed in the issue above.

**Comment by andrealin** [comment]
@amanda-phet could you please take at latest version of [proportion playground](http://phettest.colorado.edu/proportion-playground/proportion-playground_en.html?ea&brand=phet) ? ( vpn needed to look at phettest) The necklace with one round bead now has the same shape as a necklace with any number of round beads, same with the necklace with one square bead. No rush, but happy to hear your feedback if you have it. Feel free to close this issue if you like the design.

**Comment by amanda-phet** [comment]
I got the VPN working- looks great!
