### ISSUE TITLE
precarious proximity of reset buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#89]
This layout (necklace scene) seems a bit precarious, putting the "reset scene" and Reset All buttons so close to each other.

![screenshot_257](https://cloud.githubusercontent.com/assets/3046552/25824396/7ce07a5a-33fc-11e7-937b-498b2fea1a2f.png)

**Comment by jonathanolson** [comment]
I'm definitely open to any suggestions. @amanda-phet, thoughts on whether an alternate solution (maybe even on the left side) would be better?

**Comment by pixelzoom** [comment]
Data points: In Unit Rates and Equality Explorer, we are putting the reset button to the left of the scales.  The rationale was that it would less likely to be accidentally hit by right-handed students, and was unlikely to be confused with the Reset All button.

**Comment by amanda-phet** [comment]
Given the new standard to have this button on the left I think this is probably the right call. I'm not sure of the best placement though, but low makes sense to be consistent with the other scenes. 

<img width="867" alt="screen shot 2017-05-09 at 1 26 49 pm" src="https://cloud.githubusercontent.com/assets/7852916/25868949/c1edb1e8-34bb-11e7-9ed7-73c933da7c87.png">

<img width="670" alt="screen shot 2017-05-09 at 1 28 30 pm" src="https://cloud.githubusercontent.com/assets/7852916/25868951/c5ac6ca2-34bb-11e7-9a05-335800847f60.png">

**Comment by pixelzoom** [comment]
Hmmm... That reset button sure moves around a lot.  For some of the ratio views, it's centered over the AB (1/2) switch.  And putting it on the right is a little problematic with the balloons scene, because the gradient radio buttons are over there.   The only scenario that's actually "precarious" is the one shown in my original screenshot.  Maybe just address that one by shifting the reset button a bit to the left, closer to the right-side pickers?

**Comment by pixelzoom** [comment]
... or reduce the height of the Pattern display and put the rest button above the 1/2 switch, where it is in other ratio views?

**Comment by amanda-phet** [comment]
>And putting it on the right is a little problematic with the balloons scene, because the gradient radio buttons are over there.

I think you mean *left* here. I agree.

Unfortunately, we have discussed the location(s) of this button for quite a while and settled on the current semi-consistent behavior. I don't think we can reduce the height of the pattern display. In the worst-case scenario, this seemed as small as we could go with the bead size. 

<img width="1070" alt="screen shot 2017-05-09 at 2 35 43 pm" src="https://cloud.githubusercontent.com/assets/7852916/25871553/2370dcf2-34c5-11e7-91f1-a67b79ece994.png">

So, I think we should leave the button where it is (which is consistent with the visibility button on the Predict screen). If a user accidentally clicks refresh instead of reset, the damage is not that great, because the only difference is resetting the 1/2 toggle.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> So, I think we should leave the button where it is

Sounds good.  Nothing to change, so closing at "won't fix".
