### ISSUE TITLE
misc REVIEW comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#94]
I added REVIEW comments in the source code for miscellaneous things that didn't warrant their own issue.

**Comment by pixelzoom** [comment]
Related to code review #69.

**Comment by jonathanolson** [comment]
@pixelzoom, can you check https://github.com/phetsims/proportion-playground/commit/7e865395d9f185b80b5f53747f17f2a74df4471d to see if that's acceptable? I originally had a inline function in a derived property that created a long/confusing line so broke it out separately. I essentially reverted that but broke out the 'watched properties' for readability. Is that acceptable?

**Comment by jonathanolson** [comment]
Also may be good to discuss nested functions. I also saw a similar comment in AppleGraphNode:
```js
//REVIEW move updateIndicator out of constructor, it requires no access to instance fields
```

My original instinct is to keep small helper functions "inline" in front of the code that uses them, since they won't have other usages.

As a general rule, should I be more keen on putting these at the "top-level" scope (or as static methods on the type?)

**Comment by jonathanolson** [comment]
I'd also like advice on the following line:
```js
var TWO_BEAD_OFFSET = BEAD_DIAMETER - 7; //REVIEW document, not obvious what this is
```

So... I agree, it's definitely not obvious. It seems to be half the amount that the second bead (in one of the two-bead patterns) is shifted over x-wise from the origin.

The priorities seemed to be to keep the current behavior for shape, and I've had to add some workarounds (like properly re-centering the given shapes, thus the containerTranslation).

In your opinion, is it acceptable to leave a comment like "The horizontal offset in two-bead shapes from the vertical center-line to the beads"? The "best" way would be to refactor all of the custom curves/positioning so things are curves centered about the origin created with a shared parameterized function (instead of many "magic" constants with custom x,y values for each curve). It didn't seem worth the time.

**Comment by pixelzoom** [comment]
@jonathanolson asked:
> As a general rule, should I be more keen on putting these at the "top-level" scope (or as static methods on the type?)

If they aren't part of the public interface, then "top-level" scope.  I think keeping unnecessary things out of the constructor is a good general habit. Especially in common code, where one shouldn't make assumptions about how many times a type may be instantiated.  

FYI, I've been putting private functions after the namespace `register` call, so that the constructor is still as close to the top of the file as possible (e.g. `ExploreScreen` and `SceneRatioControl`).

**Comment by pixelzoom** [comment]
@jonathanolson asked:
> In your opinion, is it acceptable to leave a comment like "The horizontal offset in two-bead shapes from the vertical center-line to the beads"? ....

I think a comment is fine at this point, not worth the risk in making a major change.  But perhaps your comment should be what you said in this issue:

```js
// The horizontal offset in two-bead shapes from the vertical center-line to the beads. 
// The "best" way would be to refactor all of the custom curves/positioning so things are 
// curves centered about the origin created with a shared parameterized function 
// (instead of many "magic" constants with custom x,y values for each curve).  
// But this didn't seem to be worth the time/risk.
```

**Comment by jonathanolson** [comment]
Handled all inline REVIEW comments, commits are tagged to this issue (above).
